# Generated by Django 2.2.7 on 2019-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OS', 'Operating System'), ('OF', 'Office Software')], default='OS', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('OS', 'Operating System'), ('OF', 'Office Software')], default='p', max_length=1),
        ),
    ]
