# Generated by Django 3.0rc1 on 2019-11-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191114_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ED', 'Education'), ('BS', 'Business'), ('DS', 'Design'), ('SC', 'Security'), ('GM', 'Games')], default='BS', max_length=2),
        ),
    ]
