# Generated by Django 3.0rc1 on 2019-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191129_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ED', 'Education'), ('BS', 'Business'), ('DS', 'Design'), ('SC', 'Security'), ('GM', 'Games')], default='BS', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='core.Category'),
        ),
    ]
