# Generated by Django 3.0rc1 on 2019-11-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
