# Generated by Django 3.0 on 2019-12-07 13:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0018_auto_20191207_1048"),
    ]

    operations = [
        migrations.RenameModel(old_name="Brands", new_name="Brand",),
    ]
