# Generated by Django 3.0 on 2019-12-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(choices=[('MICROSOFT', 'Microsoft'), ('ADOBE', 'Adobe'), ('AVAST', 'Avast'), ('KASPERSKY', 'Kaspersky'), ('NORTON', 'Norton')], default='MICROSOFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('BUSINESS', 'Business'), ('DESIGN', 'Design'), ('SECURITY', 'Security'), ('GAMES', 'Games')], default='BUSINESS', max_length=20),
        ),
    ]
